print(" BEM VINDO A CALCULADORA DE NUMEROS INTEIROS ")
numero1 = int(input("Insira aqui o primeiro número: "))
numero2 = int(input("Insira aqui o segundo número: "))
soma = (numero1 + numero2)
sub = (numero1 - numero2)
multi = (numero1 * numero2)
div = (numero1 / numero2)
print("----------------------------")
print("   SEGUE ABAIXO OPERAÇÕES SIMPLES DA CALCULADORA ")
if (numero2 > numero1) :
    soma = (numero2 + numero1)
    sub = (numero2 - numero1)
    multi = (numero2 * numero1)
    div = (numero2 / numero1)
print("Soma: ", soma )
print("Subtração: ", sub )
print("Multiplicação: ", multi)
print("Divisão: ", div)